# Generated by Django 2.0.7 on 2018-07-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaches',
            name='c_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_taught', to='mainApp.c_class'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught', to='mainApp.Subject'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_by', to='mainApp.Teacher'),
        ),
    ]
